---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-elasticsearch-yaml-config
data:
  elasticsearch.yml: |
    cluster.name: "k8s-logs"
    node.name: "${NODE_NAME}"
    network.host: "0.0.0.0"
    discovery.seed_hosts: "${DISCOVERY_SEED_HOSTS}"
    cluster.initial_master_nodes: "${CLUSTER_INITIAL_MASTER_NODES}"
    xpack.monitoring.collection.enabled: "true"
    xpack.license.self_generated.type: "trial"
    xpack.security.enabled: "${XPACK_SECURITY_ENABLED}"
    xpack.security.http.ssl.enabled: "${XPACK_SECURITY_HTTP_SSL_ENABLED}"
    xpack.security.transport.ssl.enabled: "${XPACK_SECURITY_TRANSPORT_SSL_ENABLED}"