---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          # Add a hard requirement for each elastic-search pod to be deployed to a different node
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - elasticsearch
            topologyKey: "kubernetes.io/hostname"
          # Add a soft requirement for each elastic-search pod to be deployed to a different AZ
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - elasticsearch
              topologyKey: "failure-domain.beta.kubernetes.io/zone"

      initContainers:

      - name: fix-permissions
        image: busybox
        command: [ "sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data" ]

        securityContext:
          privileged: true

        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data

      - name: increase-vm-max-map
        image: busybox
        command: [ "sysctl", "-w", "vm.max_map_count=262144" ]

        securityContext:
          privileged: true

      - name: increase-fd-ulimit
        image: busybox
        command: [ "sh", "-c", "ulimit -n 65536" ]

        securityContext:
          privileged: true

      - name: create-certs
        image: gcr.io/ping-identity/ping-cloud-enrichment-bootstrap/ping-cloud-enrichment-bootstrap:7.8.0.1
        workingDir: /scripts
        command: ["sh", '$(CONTAINER_NAME).sh']

        securityContext:
          runAsUser: 0
          runAsGroup: 0

        env:
        - name: CONTAINER_NAME
          value: "create-certs"
        - name: CERTS_DIR
          value: "/enrichment-shared-volume/certs"
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/data/config"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
          readOnly: false
        - name: enrichment-shared-volume
          mountPath: /enrichment-shared-volume
          readOnly: false
        - name: enrichment-certs-config
          mountPath: /usr/share/elasticsearch/data/config/instances.yml
          subPath: instances.yml
          readOnly: true

      - name: create-passwords
        image: gcr.io/ping-identity/ping-cloud-enrichment-bootstrap/ping-cloud-enrichment-bootstrap:7.8.0.1
        workingDir: /scripts
        command: ["sh", '$(CONTAINER_NAME).sh']

        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

        env:
        - name: CONTAINER_NAME
          value: "create-passwords"
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/data/config"

        - name: CHECK_SERVICE_URL
          value: "http://127.0.0.1"
        - name: CHECK_SERVICE_PORT
          value: "9200"
        - name: DESIRED_STATUS
          value: "green"

        - name: network.host
          value: "127.0.0.1"
        - name: discovery.type
          value: "single-node"
        - name: xpack.license.self_generated.type
          value: "trial"
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.authc.anonymous.username
          value: "anonymous_user"
        - name: xpack.security.authc.anonymous.roles
          value: "superuser"

        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              name: elk-secrets
              key: ELASTIC_USER_B64
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elk-secrets
              key: ELASTIC_PASSWORD_B64
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elk-secrets
              key: LOGSTASH_USER_B64
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elk-secrets
              key: LOGSTASH_PASSWORD_B64
        - name: KIBANA_USER
          valueFrom:
            secretKeyRef:
              name: elk-secrets
              key: KIBANA_USER_B64
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elk-secrets
              key: KIBANA_PASSWORD_B64

        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
          readOnly: false
        - name: enrichment-shared-volume
          mountPath: /enrichment-shared-volume
          readOnly: false

      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0

        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 100m

        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP

        env:

        - name: CONTAINER_NAME
          value: "elasticsearch"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/data/config"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: cluster.name
          value: "k8s-logs"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: network.publish_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: network.host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: discovery.seed_hosts
          value: "es-cluster-0"
        - name: xpack.monitoring.collection.enabled
          value: "true"
        - name: xpack.license.self_generated.type
          value: "trial"
        - name: xpack.security.enabled
          value: "true"

        - name: xpack.security.http.ssl.enabled
          value: "true"
        - name: xpack.security.http.ssl.verification_mode
          value: "certificate"
        - name: xpack.security.http.ssl.client_authentication
          value: "optional"
        - name: xpack.security.http.ssl.key
          value: "certs/elasticsearch/elasticsearch.key"
        - name: xpack.security.http.ssl.certificate
          value: "certs/elasticsearch/elasticsearch.crt"
        - name: xpack.security.http.ssl.certificate_authorities
          value: "certs/ca/ca.crt" 

        - name: xpack.security.transport.ssl.enabled
          value: "true"
        - name: xpack.security.transport.ssl.verification_mode
          value: "certificate"
        - name: xpack.security.transport.ssl.client_authentication
          value: "optional"
        - name: xpack.security.transport.ssl.key
          value: "certs/elasticsearch/elasticsearch.key"
        - name: xpack.security.transport.ssl.certificate
          value: "certs/elasticsearch/elasticsearch.crt"
        - name: xpack.security.transport.ssl.certificate_authorities
          value: "certs/ca/ca.crt"

        - name: xpack.security.authc.realms.native.native1.order
          value: "0"

        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: enrichment-shared-volume
          mountPath: /enrichment-shared-volume
          readOnly: false

      volumes:
        - name: enrichment-shared-volume
          nfs:
            server: ${EFS_FILESYSTEM_ID}.efs.${REGION}.amazonaws.com
            path: /
        - name: enrichment-elasticsearch-yaml-config
          configMap:
            name: enrichment-elasticsearch-yaml-config
        - name: enrichment-certs-config
          configMap:
            name: enrichment-certs-config
        - name: enrichment-elasticsearch-ilm-policies
          configMap:
            name: enrichment-elasticsearch-ilm-policies
        - name: enrichment-elasticsearch-index-bootstraps
          configMap:
            name: enrichment-elasticsearch-index-bootstraps
        - name: enrichment-elasticsearch-index-templates
          configMap:
            name: enrichment-elasticsearch-index-templates
        - name: enrichment-elasticsearch-role-bootstraps
          configMap:
            name: enrichment-elasticsearch-role-bootstraps
            
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: elasticsearch-gp2
      resources:
        requests:
          storage: 10Gi

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-io1
  labels:
    app: elasticsearch
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  fsType: ext4
  iopsPerGB: "50"
mountOptions:
  - discard

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-gp2
  labels:
    app: elasticsearch
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
mountOptions:
  - discard

---
apiVersion: v1
kind: Secret
metadata:
  name: elk-secrets
type: Opaque
data:
  ELASTIC_USER_B64: ${ELASTIC_USER_B64}
  ELASTIC_PASSWORD_B64: ${ELASTIC_PASSWORD_B64}
  LOGSTASH_USER_B64: ${LOGSTASH_USER_B64}
  LOGSTASH_PASSWORD_B64: ${LOGSTASH_PASSWORD_B64}
  KIBANA_USER_B64: ${KIBANA_USER_B64}
  KIBANA_PASSWORD_B64: ${KIBANA_PASSWORD_B64}