apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-cache
data:
  # This is a list of what you consider to be normal countries.
  KnownCountries.yml: |-
    "United States": "YES"
    "Canada": "YES"

  # This is a list of what you consider to be malicious countries.
  MaliciousCountries.yml: |-
    "Turkey": "YES"
    "Iran": "YES"
    "Iraq": "YES"
    "North Korea": "YES"
    "Ukraine": "YES"

  # DO NOT CHANGE THIS! This is a template of alien vault IPs list that updates automatically by enrichment service
  AlienVaultIP.yml: |-
    "": "YES"

  # DO NOT CHANGE THIS! This is a template of TOR nodes list that updates by automatically enrichment service
  TorNodes.yml: |-
    "": "YES"
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: enrichment-search-template
  data:
    # This file is used for alerting in case of finding that connected client located more than 1200km or +-6hr
    6hr-1200km-template.json: |-
      {
        "query": {
          "bool": {
            "must": [],
            "filter": [
              {
                "bool": {
                  "filter": [
                    {
                      "bool": {
                        "filter": [
                          {
                            "range": {
                              "@timestamp": {
                                "gte": "now-6h/h",
                                "lte": "now"
                              }
                            }
                          },
                          {
                            "bool": {
                              "should": [
                                {
                                  "match": {
                                    "status": "success"
                                  }
                                }
                              ],
                              "minimum_should_match": 1
                            }
                          },
                          {
                            "bool": {
                              "should": [
                                {
                                  "match": {
                                    "event": "AUTHN_ATTEMPT"
                                  }
                                }
                              ],
                              "minimum_should_match": 1
                            }
                          },
                          {
                            "bool": {
                              "should": [
                                {
                                  "match": {
                                    "subject": "\"%{[subject]}\""
                                  }
                                }
                              ],
                              "minimum_should_match": 1
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ],
            "should": [],
            "must_not" : {
                "geo_distance" : {
                    "distance" : "1200km",
                    "geoip.location" : {
                        "lat"  : "%{[geoip][location][lat]}",
                        "lon"  : "%{[geoip][location][lon]}" 
                    }
                 }
             }
          }
        },
        "size" : 1,
        "sort": [
          {
            "@timestamp": {
              "order": "desc"
            }
          }
        ],
        "_source": ["subject", "geoip.location.lat", "geoip.location.lon", "geoip.country_name","geoip.city_name", "protocol", "ip", "malicious_country", "suspicious_country", "_id" ]  
      }
