# This service exposes the Kibana http port to the cluster.
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    name: http
  selector:
    app: kibana

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      initContainers:
      - name: kibana-init
        image: busybox
        workingDir: /scripts
        command: ["sh", '$(CONTAINER_NAME).sh']
        env:
        - name: WAIT_FOR
          value: "elasticsearch-init"
        - name: CONTAINER_NAME
          value: "kibana-init"
        volumeMounts:
        - name: enrichment-shared-volume
          mountPath: /enrichment-shared-volume
          readOnly: false
        - name: enrichment-scripts
          mountPath: /scripts
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: https://elasticsearch:9200
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: elasticsearch-secrets
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-secrets
                key: password
          - name: SERVER_PORT
            value: "5601"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
            value: "/enrichment-shared-volume/certs/ca/ca.crt"
          - name: XPACK_MONITORING_ENABLED
            value: "true"
          - name: SERVER_NAME
            value: "kibana"
          - name: SERVER_SSL_ENABLED
            value: "true"
          - name: SERVER_SSL_CERTIFICATE
            value: "/enrichment-shared-volume/certs/kibana/kibana.crt"
          - name: SERVER_SSL_KEY
            value: "/enrichment-shared-volume/certs/kibana/kibana.key"
          - name: CERTS_DIR
            value: "/enrichment-shared-volume/certs"
        ports:
        - containerPort: 5601
          name: http
        volumeMounts:
          - mountPath: /enrichment-shared-volume
            name: enrichment-shared-volume
            readOnly: false
          # - mountPath: /tmp/elasticsearch-secrets
          #   name: elasticsearch-secrets
      volumes:
        - name: enrichment-shared-volume
          nfs:
            server: ${EFS_FILESYSTEM_ID}.efs.${REGION}.amazonaws.com
            path: /
        - name: enrichment-scripts
          configMap:
            name: enrichment-scripts
            defaultMode: 0555
        - name: elasticsearch-secrets
          secret:
            secretName: elasticsearch-secrets